---
- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
     name: flathub
     state: present
     flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
     method: user

- name: enable copr for joplin
  command: "dnf copr enable -y taw/joplin"
  args:
     creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:taw:joplin.repo

- name: install joplin
  package:
     name: joplin
     state: present
     update_cache: yes

- name: enable copr for signal desktop
  command: "dnf copr enable -y luminoso/Signal-Desktop"
  args:
     creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:luminoso:Signal-Desktop.repo

- name: install signal desktop
  package:
     name: signal-desktop
     state: present
     update_cache: yes

- name: Install nextcloud client
  package:
     name: nextcloud-client
     state: present

- name: create apps folder for appImages
  file:
     path: "{{ ansible_env.HOME }}/apps"
     state: directory

- name: Download trueFire AppImage
  get_url:
     url: https://truefire.com/player/TrueFireInstaller.AppImage
     dest: "{{ ansible_env.HOME }}/apps/TrueFireInstaller.AppImage"

- name: install teamViewer repo
  dnf:
     name: https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
     state: latest

- name: install teamViewer
  package:
     name: teamviewer
     state: present

- name: install skype repository
  get_url:
     url: https://repo.skype.com/rpm/stable/skype-stable.repo
     dest: /etc/yum.repos.d/skype-stable.repo

- name: install skype and spotify package
  package:
     name:
        - skypeforlinux
     #    - lpf-spotify-client
     state: present

# - name: execute spotify installer
#   command: "lpf update"

- name: Install the spotify flatpak
  flatpak:
     name: https://flathub.org/repo/appstream/com.spotify.Client.flatpakref
     state: present
     remote: flathub

- name: install additional tools
  package:
     name:
        - calibre
        - musescore
        - transmission
        - mediawriter
        - android-file-transfer
        - anki
        - neovim
        - thunderbird
        - chromium
        - filezilla
     state: present
# - name: install airtame
#   flatpak:
#      name: com.airtame.Client
#      state: present
#      remote: flathub
