---
---
- name: multimedia post-install
  shell: 'dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y'

- name: install sound-and-video complement package
  shell: "dnf groupupdate sound-and-video -y"

- name: install texlive
  package:
     name: texlive-scheme-tetex
