---
- name: multimedia post-install
  package:
     name: "@multimedia"
     state: present
     #  install_weak_deps: no
     #  exclude: PackageKit-gstreamer-plugin

- name: install sound-and-video complement package
  package:
     name: "@sound-and-video"
     state: present

- name: install audio apps
  package:
     name:
        - audacity
        - pavucontrol
        - soundconverter
        - vdpauinfo
        - v4l2loopback
        - transmission
     state: present
