---
- name: multimedia post-install
  package:
     name: "@multimedia"
     state: present
     install_weak_deps: no
     exclude: PackageKit-gstreamer-plugin

- name: install sound-and-video complement package
  package:
     name: "@sound-and-video"
     state: present
# - name: install texlive
#   package:
#      name: texlive-scheme-tetex
