- hosts: localhost
  tasks:
    - name: Install gpg2
      become: yes
      package:  
        name: gnupg2
        state: present

    - name: Install tmux
      become: yes
      package: 
        name: tmux
        state: present

    - name: Install openJDK 8
      become: yes
      package: 
        name: openjdk-8-jdk
        state: present

    - name: Install openJDK 11
      become: yes
      package: 
        name: openjdk-11-jdk
        state: present

    # - name: Install Spotify
    #   become: yes
    #   package:
    #     name:
    #     state: present

    - name: Install mono
      become: yes
      package:
        name: mono-devel
        state: present

    - name: Install dotnetcore 2.2
      become: yes
      package:
        name: dotnet-sdk-2.2
        state: present

    - name: Install dotnetcore 3.0
      become: yes
      package:
        name: dotnet-sdk-3.0
        state: present

    - name: Install git
      become: yes
      package:
        name: git
        state: present

    # - name: Install nvm
    #   become: yes
    #   package:
    #     name:
    #     state: present

    # - name: Install vsCode
    #   become: yes
    #   package:
    #     name:
    #     state: present

    # - name: Install jetbrains Toolbox
    #   become: yes
    #   package:
    #     name:
    #     state: present

    - name: Install zsh-shell
      become: yes
      package:
        name: zsh
        state: present

    # - name: Install oh-my-zsh
    #   become: yes
    #   package:
    #     name:
    #     state: present


# chrome, chromium
# pyenv, 
# appimages - nextCloud
# ranger, nnn,
# texstudio
# texlive
# vim
# gimp
# vlc

# extensions and fonts via gitrepos