---
- name: install gradle completion
  git:
    repo: git://github.com/gradle/gradle-completion
    version: master
    dest: "~/.oh-my-zsh/custom/plugins/gradle-completion"

- name: install zsh-auto suggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    version: master
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: install syntax highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    version: master
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: install pyenv completion
  git:
    repo: git clone https://github.com/pyenv/pyenv.git
    version: master
    dest: "~/.pyenv"
# - name: install nerdfont
# command: curl https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/Meslo.zip

- name: install spaceship theme
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: "$ZSH_CUSTOM/themes/spaceship-prompt"

- name: Create a symbolic link
  file:
    src: $ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme
    dest: $ZSH_CUSTOM/themes/spaceship.zsh-theme
    # owner: foo
    # group: foo
    state: link
# ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
