---
- name: update packages
  dnf:
    name: "*"
    state: latest

- name: install the 'Development tools' package group
  dnf:
    name: "@Development tools"
    state: present

- name: install plugins core
  dnf:
    name: dnf-plugins-core
    state: latest

- name: get Fedora version
  command: rpm -E %fedora
  register: fedora_version
  args:
    warn: false

- name: install rpmfusion
  dnf:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version.stdout }}.noarch.rpm"
    state: latest

- name: import pubKey of microsoft repo
  rpm_key: 
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: create repo entry for vs code
  yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    file: vscode

- name: import google chrome repo
  yum_repository:
    name: google-chrome
    description: google-chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: yes
    gpgcheck: true
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    file: google-chrome

- name: Install basic packages
  package:
    name:
      - vim
      - zsh
      - tmux
      - code
      - gnupg2
      - util-linux-user
      - vagrant
      - VirtualBox
      - flatpak
      - curl
      - git
      - i3
      - ripgrep
      - php-cli
      - golang
      - gnome-shell-extension-pomodoro
      - vlc
      - trash-cli
      - tilix
      - ranger
      - nnn
      - neofetch
      - htop
      - gimp
      - podman
      - the_silver_searcher
      - fuse-exfat
      - filezilla
      - chromium
      - google-chrome
      - gnome-latex
      - texlive-scheme-tetex
    state: present
    update_cache: yes

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: autoremove uneeded packages
  dnf:
    autoremove: yes
  ignore_errors: yes
