---
# - name: install basic packages
#   import_tasks: common.yml

# - name: install multimedia packages
#   import_tasks: multimedia.yml

- name: config and install zsh related stuff
  import_tasks: zsh.yml
# - name: install java and jvm dev packages
#   import_tasks: java.yml

# - name: config and install vim related stuff
#   import_tasks: vim8.yml

# - name: install sipgate workstation add-ons
#   import_tasks: sipgate.yml
