# - name: Download nextCloud appImage
#   get_url: https://download.nextcloud.com/desktop/releases/Linux/latest
#   dest: "{{ ansible_env.HOME }}/apps/"

- name: Install nextcloud client
  package:
    name: nextcloud-client
    state: present

- name: Download trueFire AppImage
  get_url: https://truefire.com/player/TrueFireInstaller.AppImage
  dest: "{{ ansible_env.HOME }}/apps/"

# desktop wallpaper

- name: Remove Rhythmbox
  become: yes
  package:
    name: rhythmbox
    state: absent

- name: install teamViewer repo
  dnf:
    name: https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
    state: latest

- name: install teamViewer
  package:
    name: teamviewer

- name: install skype repository
  get_url:
    url: https://repo.skype.com/rpm/stable/skype-stable.repo
    dest: /etc/yum.repos.d/skype-stable.repo

- name: install skype and spotify package
  package:
    name:
      - skypeforlinux
      - lpf-spotify-client
    state: present

# - name: execute spotify installer
#   command: "lpf update"

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

# - name: Install the spotify flatpak
#   flatpak:
#     name: https://flathub.org/repo/appstream/com.spotify.Client.flatpakref
#     state: present
#     remote: flathub

- name: Install the signal flatpak
  flatpak:
    name: https://flathub.org/repo/appstream/org.signal.Signal.flatpakref
    state: present

- name: multimedia post-install
  shell: 'dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y'

- name: install sound-and-video complement package
  shell: "dnf groupupdate sound-and-video -y"
