---
- name: change shell to zsh for root
  command: "chsh -s /bin/zsh vagrant" #root

- name: change shell to zsh for user
  command: "chsh -s /bin/zsh {{ ansible_ssh_user }}"

# nerdfonts

- name: Get oh-my-zsh installer
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "{{ ansible_env.HOME }}/install.sh"

- name: Install oh-my-zsh
  command: "sh ~/install.sh"
  ignore_errors: yes

- name: install gradle completion
  git:
    repo: git://github.com/gradle/gradle-completion
    version: master
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/gradle-completion"

- name: install zsh-auto suggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    version: master
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: install syntax highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    version: master
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: create user font directory
  file:
    path: "{{ ansible_env.HOME }}/.fonts"
    state: directory

- name: download and unzip NerdFont
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/Meslo.zip
    dest: "{{ ansible_env.HOME }}/.fonts/"
    remote_src: yes

- name: install spaceship theme
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship-prompt"

- name: Create a symbolic link
  file:
    src: ~/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme
    dest: ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme
    # owner: foo
    # group: foo
    state: link
# - name: Get zsh dotfile
#   git:
#     repo:
#     dest: "{{ ansible_env.HOME }}/.zshrc"
