---
- name: change shell to zsh for root
  command: "chsh -s /bin/zsh root"

- name: change shell to zsh for user
  command: "chsh -s /bin/zsh {{ ansible_ssh_user }}"

- name: Get oh-my-zsh installer
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "{{ ansible_env.HOME }}/install.sh"

- name: Install oh-my-zsh
  command: "{{ ansible_env.HOME }}/install.sh"
  ignore_errors: yes

- name: install gradle completion
  git:
    repo: git://github.com/gradle/gradle-completion
    version: master
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/gradle-completion"

- name: install zsh-auto suggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    version: master
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: install syntax highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    version: master
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: install spaceship theme
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship-prompt"

- name: Create a symbolic link
  file:
    src: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
    state: link
