---
- name: install i3 and deps for config
  package:
     name:
        - i3-gaps
        - i3status
        - compton
        - feh
        - dunst
        - rofi
        - pango
        - numlockx
        - network-manager-applet
        - lxappearance
        - py3status
        - xautolock
        - yad
        - qutebrowser
        - i3lock
     state: present
