---
- name: enable copr for i3-gaps repo
  command: "dnf copr enable -y gregw/i3desktop"
  args:
     creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:gregw:i3-gaps.repo

- name: install i3 and deps for config
  package:
     name:
        - i3-gaps
        - i3status
        - compton
        - feh
        - dunst
        - rofi
        - pango
        - numlockx
        - network-manager-applet
        - lxappearance
        - py3status
        - xautolock
        - yad
        - i3lock
     state: present
     update_cache: yes
