---
- name: install gradle completion
  git:
     repo: git://github.com/gradle/gradle-completion
     version: master
     dest: "{{ zsh_custom }}/plugins/gradle-completion"

- name: install zsh-auto suggestions
  git:
     repo: https://github.com/zsh-users/zsh-autosuggestions
     version: master
     dest: "{{ zsh_custom }}/plugins/zsh-autosuggestions"

- name: install syntax highlighting
  git:
     repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
     version: master
     dest: "{{ zsh_custom }}/plugins/zsh-syntax-highlighting"

- name: install spaceship theme
  git:
     repo: https://github.com/denysdovhan/spaceship-prompt.git
     dest: "{{ zsh_custom }}/themes/spaceship-prompt"

- name: Create a symbolic link
  file:
     src: "{{ zsh_custom }}/themes/spaceship-prompt/spaceship.zsh-theme"
     dest: "{{ zsh_custom }}/themes/spaceship.zsh-theme"
     state: link
