---
- name: install nvidia-driver
  package:
     name:
        - akmod-nvidia
        - vdpauinfo
        - libva-vdpau-driver
        - libva-utils

- name: nvidia prime support
  shell: |
     cat > /etc/modprobe.d/nvidia.conf <<EOF
     # Enable DynamicPwerManagement
     # http://download.nvidia.com/XFree86/Linux-x86_64/440.31/README/dynamicpowermanagement.html
     options nvidia NVreg_DynamicPowerManagement=0x02
     EOF
