---
- name: create user font directory
  file:
     path: "{{ ansible_env.HOME }}/.fonts"
     state: directory

- name: download and unzip NerdFont
  unarchive:
     src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/Meslo.zip
     dest: "{{ ansible_env.HOME }}/.fonts/"
     remote_src: yes
