---
- name: enable copr for joplin
  command: "dnf copr enable -y taw/joplin"
  args:
     creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:taw:joplin.repo

- name: install joplin
  package:
     name: joplin
     state: present
     update_cache: yes

- name: enable copr for signal desktop
  command: "dnf copr enable -y luminoso/Signal-Desktop"
  args:
     creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:luminoso:Signal-Desktop.repo

- name: install signal desktop
  package:
     name: signal-desktop
     state: present
     update_cache: yes

- name: enable copr for flat-remix-icons
  command: "dnf copr enable -y daniruiz/flat-remix"
  args:
     creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:daniruiz:flat_remix.repo

- name: install flat-remix-icons
  package:
     name: flat-remix
     state: present
     update_cache: yes

- name: Enable Night Light
  dconf:
     key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
     value: true

- name: Set Night Light Temperature
  dconf:
     key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
     value: uint32 5500

- name: install AdMin theme prerequisites
  package:
     name: sassc
     state: present

- name: get AdMin theme resources
  git:
     repo: https://github.com/nrhodes91/AdMin
     dest: "{{ ansible_env.HOME }}/.themes/AdMin"

- name: create symlinks from admin repo to user-themes folder
  command: for theme in ~/.themes/AdMin/admin-gtk*; do ln -sf $theme ~/.themes/; done

- name: compile sass from AdMin theme
  command: find ~/.themes/AdMin -type f -name parse-sass.sh -execdir {} \;

- name: create user font directory
  file:
     path: "{{ ansible_env.HOME }}/.fonts"
     state: directory

- name: download and unzip NerdFont
  unarchive:
     src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/Meslo.zip
     dest: "{{ ansible_env.HOME }}/.fonts/"
     remote_src: yes

- name: install additional tools
  package:
     name:
        - calibre
        - museScore
        - transmission
        - mediawriter
        - android-file-transfer
     state: present

- name: install gnome tweaks and some shell extensions
  package:
     name:
        - gnome-tweaks
        - gnome-shell-extension-user-theme
        - gnome-shell-extension-dash-to-dock
        - gnome-shell-extension-desktop-icons
        - gnome-shell-extension-pomodoro
        - gnome-latex
     state: present
###- name: setup printer??
###- name: desktop wallpaper
