---
- name: import pubKey of microsoft repo
  rpm_key:
     state: present
     key: https://packages.microsoft.com/keys/microsoft.asc

- name: create repo entry for vs code
  yum_repository:
     name: code
     description: Visual Studio Code
     baseurl: https://packages.microsoft.com/yumrepos/vscode
     enabled: yes
     gpgcheck: true
     gpgkey: https://packages.microsoft.com/keys/microsoft.asc
     file: vscode

- name: install vs code
  package:
     name: code
     state: present
     update_cache: yes
