---
- name: update packages
  become: yes
  package:
     name: "*"
     state: latest

- name: install the 'Development tools' package group
  package:
     name: "@Development tools"
     state: present

- name: install plugins core
  package:
     name: dnf-plugins-core
     state: latest

- name: install rpmfusion
  package:
     name:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
     state: latest

- name: install basic packages
  package:
     name:
        - ansible
        - ack
        - curl
        - flatpak
        - fzf
        - ffmpeg
        - fuse-exfat
        - gimp
        - git
        - gparted
        - gnupg2
        - htop
        - imwheel
        - lshw
        - neofetch
        - podman
        - ripgrep
        - the_silver_searcher
        - tilix
        - tmux
        - trash-cli
        - util-linux-user
        - vagrant
        - vim
        - vifm
        - virt-manager
        - VirtualBox
        - vlc
        - zsh
        - zathura
        - zathura-plugins-all
     state: present
     update_cache: yes
