---
- name: update packages
  package:
     name: "*"
     state: latest

- name: install the 'Development tools' package group
  package:
     name: "@Development tools"
     state: present

- name: install plugins core
  package:
     name: dnf-plugins-core
     state: latest

- name: install rpmfusion
  package:
     name:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
     state: latest

- name: install basic packages
  package:
     name:
        - curl
        - chromium
        - filezilla
        - flatpak
        - fuse-exfat
        - gimp
        - git
        - gnupg2
        - htop
        - i3
        - neofetch
        - nnn
        - podman
        - ranger
        - ripgrep
        - the_silver_searcher
        - tilix
        - tmux
        - trash-cli
        - util-linux-user
        - vagrant
        - vim
        - VirtualBox
        - vlc
        - zsh
     state: present
     update_cache: yes
