---
- name: setup docker CE repo
  command: "dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"
  args:
     creates: /etc/yum.repos.d/docker-ce.repo

- name: install docker CE
  package:
     name: docker-ce
     state: present
     update_cache: yes

- name: register and start docker service
  systemd:
     state: started
     enabled: yes
     name: docker

- name: create docker group for user
  command: "groupadd docker"
  ignore_errors: yes

- name: add user to docker
  command: "usermod -aG docker {{ ansible_ssh_user }}"
