---
- name: install vim-live-latex-deps
  package:
     name:
        - mupdf
        - xdotool
     state: present
#vim-live-latex-preview

- name: install deps for latex-language-server
  package:
     name:
        - luarocks
        - lua-devel
     state: present

- name: install latex-language-server for vim
  shell: luarocks install digestif --local
